#ifndef AIRPORT_GRAPHS_SIMULATOR_SOUNDMANIPULATOR_H
#define AIRPORT_GRAPHS_SIMULATOR_SOUNDMANIPULATOR_H

void finalSound();

void initialSound();

void playSound(const char *soundFile);

#endif //AIRPORT_GRAPHS_SIMULATOR_SOUNDMANIPULATOR_H
