#ifndef AIRPORT_GRAPHS_SIMULATOR_AIRPORTSSERVICES_H
#define AIRPORT_GRAPHS_SIMULATOR_AIRPORTSSERVICES_H

void getCodeFromUser(const char prompt[], char code[]);

#endif //AIRPORT_GRAPHS_SIMULATOR_AIRPORTSSERVICES_H
